### PR TITLE
Update index.styl

### PR DESCRIPTION
**Pull request by settsu**
Reduced shadow depth and spread. (To maintain dimension but give cards appearance of being closer to table surface and not "floating" above it.)

### CODE REVIEW

**Comment by pakastin** [comment]
Thanks! Will have to resolve the conflict first though, but I'm on mobile right now..

**Comment by pakastin** [comment]
It's merged now, thanks!

**Comment by pakastin** [comment]
Thank you @settsu! ;)

**Comment by pakastin** [comment]
Thank you @settsu! ;)

**Comment by settsu** [comment]
Thanks for the interesting & inspiring demo. Cheers!

**Comment by pakastin** [comment]
It's live now! http://deck-of-cards.js.org/ ;)

**Pull request merged**
