### PR TITLE
Created a feature to alow select multiple cards and incremented examples

### PR DESCRIPTION
**Pull request by mtheus**
Hi People, I created a feature to alow select multiple cards and incremented some examples with move feature and others small changes in the code. I think this is a great feature do share with others. Thanks for yours contribuitions.

### CODE REVIEW

**Comment by mtheus** [comment]
1) Run the example
2) Move some cards
3) Click on Select - new menu item
4) Click in one or many cards
5) Click on some green empty place
6) All selected cards will move to the new position

**Comment by pakastin** [comment]
Perfect! I'm visiting Paris, I check this out when back home.. Thank you for contribution! 👍

**Comment by pakastin** [comment]
I'm unfortunately not able to get the feature working.. Could you double check everything's working?

**Comment by mtheus** [comment]
Tell me if this is helpfull http://recordit.co/75N35zz7mE or gime me more details

**Comment by pakastin** [comment]
Sorry to let you know I'm currently rewriting the project. I'll get back to you when I have things to show!

**Pull request closed without merging**
