### PR TITLE
Fixed animationFrames case ambiguity

### PR DESCRIPTION
**Pull request by mjkaufer**
The file for `animationFrames` was named `animationframes`, which was confusing to start. Then, it was imported once as `animationframes` and again as `animationFrames`, which was even more confusing. I standardized this, so now the method is `animationFrames`, as is the filename.

### CODE REVIEW

**Comment by pakastin** [comment]
Thanks! Yeah camelCasing is my weak spot because in finnish language we just write every compound together, like just camelcasing instead of camel casing :)

**Comment by mjkaufer** [comment]
That's interesting. It's not the camel case that's the problem, but rather the fact that there were two `animationFrames` methods defined - one with camelcase (`animationFrames`), and one without (`animationframes`). Should I edit my pull request so that it's lowercase instead? I.e. `animationframes`? Either way, there are still build errors - I can fix them either with or without camel case.

**Comment by pakastin** [comment]
No, of course with camelCasing like it should be - I'm on mobile now, I'll check this out and merge when on laptop. Thank you for fixing this!

**Comment by mjkaufer** [comment]
Awesome!

**Comment by pakastin** [comment]
live now!

**Pull request merged**
