### PR TITLE
Allow cards to be represented by their english names; Allow more than one deck of cards within a Deck

### PR DESCRIPTION
**Pull request by Jorl17**
See my comments here https://github.com/pakastin/deck-of-cards/issues/28#issuecomment-172033184 :)

### CODE REVIEW

**Comment by pakastin** [comment]
Could you fix rank and suit names to be lowercased? I think `rank === 'ace'` would feel more idiomatic..

I am not sure if I like the verbal ones or not. With suits it makes more sense of course, but with ranks it makes iterating harder, since you'd need to create an array of names first.

Will the modules work with multiple decks? (bysuit, fan, flip, intro, poker, shuffle, sort..?)

Is there any backward-compatibility breaking changes?

**Comment by pakastin** [comment]
Otherwise, great work! 👍

**Comment by Jorl17** [comment]
Hi!

First of all, as you might have noticed, Javascript is not my primary language, so feel fry to adjust whatever you think is not appropriate or idiomatic. I personally _dislike_ a lot of what I wrote in these commits, but I did the best I could at the time.

I will only be able to work on this in two or three days, but I'll make them lowercase (to be honest, if I were working with a language I'm more used to, I'd use an enum...strings feel icky).

Regarding backward-compatibility breaking changes, I think it is fully backwards compatible. The modules also work with multiple decks (I did some changes to them, but not many), with one exception: bysuit. It works, but for multiple decks, the results are not "expected": equal cards are stacked together. There's a FIXME for that, because I wasn't sure what to do.

I'll look into this over the coming days. Once again, thank you for your great work!

**Comment by pakastin** [comment]
ok, I'll wait for the fixes - glad to hear I've inspired you! Also check out my other projects: https://nodegarden.js.org and https://frzr.js.org ;)

**Comment by Jorl17** [comment]
Finally had some time on my hands to focus back on this. Here they are, lowercase: https://github.com/Jorl17/deck-of-cards/commit/fd6d9b0edf7d8b0e90beedb3f5c632cfa1b60c50

**Comment by pakastin** [comment]
I'm currently rewriting the project, so I will unfortunately close this PR. I'll let you know about new things as soon as it's ready to be shown!

**Pull request closed without merging**
