### PR TITLE
Packaging for Meteor

### PR DESCRIPTION
**Pull request by mizzao**
[Meteor](https://www.meteor.com/) is a web framework for building real-time, interactive apps using full-stack Javascript. It's become quite popular lately, and is in the top 10 starred GitHub projects.

I recently started building a Meteor app that involves some cards and happened upon your framework. Part of the appeal of Meteor is quick prototyping with an easy way to pull in code. With some minor changes, your repo can be directly published as a Meteor package, allowing other people to make card games and other fun stuff easily in Meteor apps.

In order to publish this as a Meteor package for this and future releases, you'd just have to [install Meteor](https://www.meteor.com/install), build the files in `dist`, then run `meteor publish` in the base repo folder.

Let me know if you have any other questions or comments.

P.S. To enhance adoption, it would be nice to make an API for the decks and cards, but the source is easy enough to browse for now.

### CODE REVIEW

**Comment by pakastin** [comment]
Thanks for contributing! I'll check this out and come back in a moment..

**Comment by pakastin** [comment]
@mizzao: How can I test if the Meteor installation will work? Sorry, but I've never used Meteor..

**Comment by mizzao** [comment]
Hey @pakastin, I don't understand what you mean by whether the Meteor installation will work. The instructions linked above are for any of Windows, OS X, or Linux.

Also in the future, Meteor will support ES6 modules as part of its own build process, so you'd be able to directly publish from `lib/` without generating the files in `dist/` first.

**Comment by pakastin** [comment]
How can I install the package in Meteor and try it out? I wouldn't want to do the pull request without knowing what will it do..

**Comment by mizzao** [comment]
Ah, ok. For an example see https://github.com/mizzao/trading-market.

Basically you can do the following to install a package locally, before it is published:

```
meteor create some-app
cd some-app
git clone https://github.com/mizzao/deck-of-cards.git packages/deck-of-cards
meteor add pakastin:deck-of-cards
```

Then you will be able to use `Deck` in any front-end code, in the same way you have written. The faces and backs are all working as well.

**Comment by pakastin** [comment]
ok, I'll check that out - give me few days time, because my laptop broke and is being fixed.. I'm on a Chromebook (ARM) right now and it's a bit limited what I can do with this.. :/

**Comment by pakastin** [comment]
Sorry it took so long, now merged!

**Pull request merged**
